//ScriptureProvider.swift

import Foundation

struct ScriptureProvider {
    struct Scripture {
        let text: String
        let reference: String
        let youVersionURL: String?
        
        init(text: String, reference: String) {
            self.text = text
            self.reference = reference
            self.youVersionURL = ScriptureProvider.generateYouVersionURL(for: reference)
        }
    }
    
    static let scriptures: [Scripture] = [
        Scripture(text: "Your word is a lamp to my feet and a light to my path.", reference: "Psalm 119:105"),
        Scripture(text: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5"),
        Scripture(text: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13"),
        Scripture(text: "Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you.", reference: "Deuteronomy 31:6"),
        Scripture(text: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1"),
        Scripture(text: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.", reference: "John 3:16"),
        Scripture(text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.", reference: "Philippians 4:6"),
        Scripture(text: "Fear thou not; for I am with thee: be not dismayed; for I am thy God.", reference: "Isaiah 41:10"),
        Scripture(text: "In the beginning God created the heaven and the earth.", reference: "Genesis 1:1"),
        Scripture(text: "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.", reference: "Matthew 6:33"),
        Scripture(text: "Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners.", reference: "Psalm 1:1"),
        Scripture(text: "Thy word have I hid in mine heart, that I might not sin against thee.", reference: "Psalm 119:11"),
        Scripture(text: "And we know that all things work together for good to them that love God.", reference: "Romans 8:28"),
        Scripture(text: "Cast thy burden upon the Lord, and he shall sustain thee.", reference: "Psalm 55:22"),
        Scripture(text: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.", reference: "Matthew 11:28"),
        Scripture(text: "The fear of the Lord is the beginning of wisdom.", reference: "Proverbs 9:10"),
        Scripture(text: "What time I am afraid, I will trust in thee.", reference: "Psalm 56:3"),
        Scripture(text: "Delight thyself also in the Lord: and he shall give thee the desires of thine heart.", reference: "Psalm 37:4"),
        Scripture(text: "Be strong and of a good courage; be not afraid, neither be thou dismayed.", reference: "Joshua 1:9"),
        Scripture(text: "Jesus saith unto him, I am the way, the truth, and the life.", reference: "John 14:6"),
        Scripture(text: "Commit thy works unto the Lord, and thy thoughts shall be established.", reference: "Proverbs 16:3"),
        Scripture(text: "Blessed are the pure in heart: for they shall see God.", reference: "Matthew 5:8"),
        Scripture(text: "Wait on the Lord: be of good courage, and he shall strengthen thine heart.", reference: "Psalm 27:14"),
        Scripture(text: "Let not your heart be troubled: ye believe in God, believe also in me.", reference: "John 14:1"),
        Scripture(text: "The Lord is my light and my salvation; whom shall I fear?", reference: "Psalm 27:1"),
        Scripture(text: "Peace I leave with you, my peace I give unto you.", reference: "John 14:27"),
        Scripture(text: "Every word of God is pure: he is a shield unto them that put their trust in him.", reference: "Proverbs 30:5"),
        Scripture(text: "God is our refuge and strength, a very present help in trouble.", reference: "Psalm 46:1"),
        Scripture(text: "Rejoice in the Lord always: and again I say, Rejoice.", reference: "Philippians 4:4"),
        Scripture(text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee.", reference: "Isaiah 26:3"),
        Scripture(text: "Ask, and it shall be given you; seek, and ye shall find.", reference: "Matthew 7:7"),
        Scripture(text: "Have not I commanded thee? Be strong and of a good courage.", reference: "Joshua 1:9"),
        Scripture(text: "My help cometh from the Lord, which made heaven and earth.", reference: "Psalm 121:2"),
        Scripture(text: "The Lord is nigh unto them that are of a broken heart.", reference: "Psalm 34:18"),
        Scripture(text: "Thy kingdom is an everlasting kingdom.", reference: "Psalm 145:13"),
        Scripture(text: "Be ye kind one to another, tenderhearted, forgiving one another.", reference: "Ephesians 4:32"),
        Scripture(text: "The Lord will give strength unto his people.", reference: "Psalm 29:11"),
        Scripture(text: "Call unto me, and I will answer thee.", reference: "Jeremiah 33:3"),
        Scripture(text: "If God be for us, who can be against us?", reference: "Romans 8:31"),
        Scripture(text: "O give thanks unto the Lord; for he is good.", reference: "Psalm 136:1"),
        Scripture(text: "Let every thing that hath breath praise the Lord.", reference: "Psalm 150:6"),
        Scripture(text: "The Lord is good, a strong hold in the day of trouble.", reference: "Nahum 1:7"),
        Scripture(text: "Ye are the light of the world. A city that is set on an hill cannot be hid.", reference: "Matthew 5:14"),
        Scripture(text: "Draw nigh to God, and he will draw nigh to you.", reference: "James 4:8"),
        Scripture(text: "The joy of the Lord is your strength.", reference: "Nehemiah 8:10"),
        Scripture(text: "I will lift up mine eyes unto the hills, from whence cometh my help.", reference: "Psalm 121:1"),
        Scripture(text: "Love one another; as I have loved you.", reference: "John 13:34"),
        Scripture(text: "The Lord bless thee, and keep thee.", reference: "Numbers 6:24"),
        Scripture(text: "Faith is the substance of things hoped for, the evidence of things not seen.", reference: "Hebrews 11:1"),
        Scripture(text: "The Lord is merciful and gracious, slow to anger, and plenteous in mercy.", reference: "Psalm 103:8"),
        Scripture(text: "With God all things are possible.", reference: "Matthew 19:26"),
        Scripture(text: "Study to shew thyself approved unto God.", reference: "2 Timothy 2:15"),
        Scripture(text: "Great is thy faithfulness.", reference: "Lamentations 3:23"),
        Scripture(text: "Blessed are they that mourn: for they shall be comforted.", reference: "Matthew 5:4"),
        Scripture(text: "The Lord is my strength and my shield.", reference: "Psalm 28:7"),
        Scripture(text: "Rest in the Lord, and wait patiently for him.", reference: "Psalm 37:7"),
        Scripture(text: "Behold, I stand at the door, and knock.", reference: "Revelation 3:20"),
        Scripture(text: "Give, and it shall be given unto you.", reference: "Luke 6:38"),
        Scripture(text: "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty.", reference: "Psalm 91:1"),
        Scripture(text: "Let your light so shine before men.", reference: "Matthew 5:16"),
        Scripture(text: "The effectual fervent prayer of a righteous man availeth much.", reference: "James 5:16"),
        Scripture(text: "Be not deceived; God is not mocked.", reference: "Galatians 6:7"),
        Scripture(text: "The Lord shall fight for you, and ye shall hold your peace.", reference: "Exodus 14:14"),
        Scripture(text: "Seek ye the Lord while he may be found.", reference: "Isaiah 55:6"),
        Scripture(text: "I am the vine, ye are the branches.", reference: "John 15:5"),
        Scripture(text: "Blessed are the peacemakers: for they shall be called the children of God.", reference: "Matthew 5:9"),
        Scripture(text: "The Lord is gracious, and full of compassion.", reference: "Psalm 111:4"),
        Scripture(text: "Trust in him at all times; ye people, pour out your heart before him.", reference: "Psalm 62:8"),
        Scripture(text: "Go ye therefore, and teach all nations.", reference: "Matthew 28:19"),
        Scripture(text: "Thou art my hiding place and my shield.", reference: "Psalm 119:114"),
        Scripture(text: "Humble yourselves in the sight of the Lord, and he shall lift you up.", reference: "James 4:10"),
        Scripture(text: "The Lord is on my side; I will not fear.", reference: "Psalm 118:6"),
        Scripture(text: "Let all your things be done with charity.", reference: "1 Corinthians 16:14"),
        Scripture(text: "Thy testimonies are very sure.", reference: "Psalm 93:5"),
        Scripture(text: "Heaven and earth shall pass away, but my words shall not pass away.", reference: "Matthew 24:35"),
        Scripture(text: "I will never leave thee, nor forsake thee.", reference: "Hebrews 13:5"),
        Scripture(text: "The fear of the Lord is the beginning of knowledge.", reference: "Proverbs 1:7"),
        Scripture(text: "Be still, and know that I am God.", reference: "Psalm 46:10"),
        Scripture(text: "Keep thy tongue from evil, and thy lips from speaking guile.", reference: "Psalm 34:13"),
        Scripture(text: "Ye shall know the truth, and the truth shall make you free.", reference: "John 8:32"),
        Scripture(text: "The Lord is good unto them that wait for him.", reference: "Lamentations 3:25"),
        Scripture(text: "Praise ye the Lord: for it is good to sing praises unto our God.", reference: "Psalm 147:1"),
        Scripture(text: "Whatsoever ye do, do it heartily, as to the Lord.", reference: "Colossians 3:23"),
        Scripture(text: "The Lord is my rock, and my fortress.", reference: "Psalm 18:2"),
        Scripture(text: "Confess your faults one to another, and pray one for another.", reference: "James 5:16"),
        Scripture(text: "O taste and see that the Lord is good.", reference: "Psalm 34:8"),
        Scripture(text: "Thy righteousness is like the great mountains.", reference: "Psalm 36:6"),
        Scripture(text: "I am come that they might have life, and that they might have it more abundantly.", reference: "John 10:10"),
        Scripture(text: "The Lord upholdeth all that fall, and raiseth up all those that be bowed down.", reference: "Psalm 145:14"),
        Scripture(text: "Be of good cheer; it is I; be not afraid.", reference: "Matthew 14:27"),
        Scripture(text: "His compassions fail not.", reference: "Lamentations 3:22"),
        Scripture(text: "Walk in love, as Christ also hath loved us.", reference: "Ephesians 5:2"),
        Scripture(text: "The Lord preserveth the faithful.", reference: "Psalm 31:23"),
        Scripture(text: "By grace are ye saved through faith.", reference: "Ephesians 2:8"),
        Scripture(text: "Thou hast turned for me my mourning into dancing.", reference: "Psalm 30:11"),
        Scripture(text: "The meek shall inherit the earth.", reference: "Psalm 37:11"),
        Scripture(text: "Teach me thy way, O Lord, and lead me in a plain path.", reference: "Psalm 27:11"),
        Scripture(text: "My grace is sufficient for thee.", reference: "2 Corinthians 12:9"),
        Scripture(text: "Let us love one another: for love is of God.", reference: "1 John 4:7"),
        Scripture(text: "Create in me a clean heart, O God; and renew a right spirit within me.", reference: "Psalm 51:10"),
        Scripture(text: "The heavens declare the glory of God; and the firmament sheweth his handywork.", reference: "Psalm 19:1"),
        Scripture(text: "Cast all your care upon him; for he careth for you.", reference: "1 Peter 5:7"),
        Scripture(text: "In all thy ways acknowledge him, and he shall direct thy paths.", reference: "Proverbs 3:6"),
        Scripture(text: "The name of the Lord is a strong tower: the righteous runneth into it, and is safe.", reference: "Proverbs 18:10"),
        Scripture(text: "And ye shall seek me, and find me, when ye shall search for me with all your heart.", reference: "Jeremiah 29:13"),
        Scripture(text: "The Lord is slow to anger, and great in power.", reference: "Nahum 1:3"),
        Scripture(text: "But my God shall supply all your need according to his riches in glory.", reference: "Philippians 4:19"),
        Scripture(text: "He that covereth his sins shall not prosper: but whoso confesseth and forsaketh them shall have mercy.", reference: "Proverbs 28:13"),
        Scripture(text: "For I know the thoughts that I think toward you, saith the Lord, thoughts of peace.", reference: "Jeremiah 29:11"),
        Scripture(text: "Blessed are they which do hunger and thirst after righteousness: for they shall be filled.", reference: "Matthew 5:6"),
        Scripture(text: "The Lord is my portion, saith my soul; therefore will I hope in him.", reference: "Lamentations 3:24"),
        Scripture(text: "Submit yourselves therefore to God. Resist the devil, and he will flee from you.", reference: "James 4:7"),
        Scripture(text: "Whoso keepeth his mouth and his tongue keepeth his soul from troubles.", reference: "Proverbs 21:23"),
        Scripture(text: "Thou art my refuge and my fortress: my God; in him will I trust.", reference: "Psalm 91:2"),
        Scripture(text: "For whosoever shall call upon the name of the Lord shall be saved.", reference: "Romans 10:13"),
        Scripture(text: "The grass withereth, the flower fadeth: but the word of our God shall stand for ever.", reference: "Isaiah 40:8"),
        Scripture(text: "Let no corrupt communication proceed out of your mouth.", reference: "Ephesians 4:29"),
        Scripture(text: "Thou, Lord, art good, and ready to forgive.", reference: "Psalm 86:5"),
        Scripture(text: "He that spared not his own Son, but delivered him up for us all.", reference: "Romans 8:32"),
        Scripture(text: "Speak, Lord; for thy servant heareth.", reference: "1 Samuel 3:9"),
        Scripture(text: "The Lord redeemeth the soul of his servants.", reference: "Psalm 34:22"),
        Scripture(text: "Order my steps in thy word: and let not any iniquity have dominion over me.", reference: "Psalm 119:133"),
        Scripture(text: "Whoso findeth me findeth life, and shall obtain favour of the Lord.", reference: "Proverbs 8:35"),
        Scripture(text: "The Lord thy God in the midst of thee is mighty.", reference: "Zephaniah 3:17"),
        Scripture(text: "Finally, brethren, whatsoever things are true, whatsoever things are honest, think on these things.", reference: "Philippians 4:8"),
        Scripture(text: "My soul, wait thou only upon God; for my expectation is from him.", reference: "Psalm 62:5"),
        Scripture(text: "Except the Lord build the house, they labour in vain that build it.", reference: "Psalm 127:1"),
        Scripture(text: "He that is slow to anger is better than the mighty.", reference: "Proverbs 16:32"),
        Scripture(text: "The Lord is righteous in all his ways, and holy in all his works.", reference: "Psalm 145:17"),
        Scripture(text: "If we confess our sins, he is faithful and just to forgive us our sins.", reference: "1 John 1:9"),
        Scripture(text: "Thy mercy, O Lord, is in the heavens; and thy faithfulness reacheth unto the clouds.", reference: "Psalm 36:5"),
        Scripture(text: "Return unto thy rest, O my soul; for the Lord hath dealt bountifully with thee.", reference: "Psalm 116:7"),
        Scripture(text: "The fear of the Lord prolongeth days.", reference: "Proverbs 10:27"),
        Scripture(text: "O Lord, thou art my God; I will exalt thee, I will praise thy name.", reference: "Isaiah 25:1"),
        Scripture(text: "Ye are bought with a price; therefore glorify God in your body.", reference: "1 Corinthians 6:20"),
        Scripture(text: "The Lord shall preserve thee from all evil: he shall preserve thy soul.", reference: "Psalm 121:7"),
        Scripture(text: "To every thing there is a season, and a time to every purpose under the heaven.", reference: "Ecclesiastes 3:1"),
        Scripture(text: "He hath shewed thee, O man, what is good; and what doth the Lord require of thee.", reference: "Micah 6:8"),
        Scripture(text: "Be ye therefore perfect, even as your Father which is in heaven is perfect.", reference: "Matthew 5:48"),
        Scripture(text: "Thou hast also given me the shield of thy salvation.", reference: "2 Samuel 22:36"),
        Scripture(text: "The Lord will perfect that which concerneth me.", reference: "Psalm 138:8"),
        Scripture(text: "Open thou mine eyes, that I may behold wondrous things out of thy law.", reference: "Psalm 119:18"),
        Scripture(text: "Keep thy heart with all diligence; for out of it are the issues of life.", reference: "Proverbs 4:23"),
        Scripture(text: "For the Lord giveth wisdom: out of his mouth cometh knowledge and understanding.", reference: "Proverbs 2:6"),
        Scripture(text: "Blessed is he whose transgression is forgiven, whose sin is covered.", reference: "Psalm 32:1"),
        Scripture(text: "I have set the Lord always before me: because he is at my right hand, I shall not be moved.", reference: "Psalm 16:8"),
        Scripture(text: "Behold, how good and how pleasant it is for brethren to dwell together in unity.", reference: "Psalm 133:1"),
        Scripture(text: "The Lord is far from the wicked: but he heareth the prayer of the righteous.", reference: "Proverbs 15:29"),
        Scripture(text: "Look unto me, and be ye saved, all the ends of the earth.", reference: "Isaiah 45:22"),
        Scripture(text: "A new heart also will I give you, and a new spirit will I put within you.", reference: "Ezekiel 36:26")
    ]
    
    private static let osisBookMap: [String: String] = [
        "Genesis": "GEN",
        "Exodus": "EXO",
        "Leviticus": "LEV",
        "Numbers": "NUM",
        "Deuteronomy": "DEU",
        "Joshua": "JOS",
        "Judges": "JDG",
        "Ruth": "RUT",
        "1 Samuel": "1SA",
        "2 Samuel": "2SA",
        "1 Kings": "1KI",
        "2 Kings": "2KI",
        "1 Chronicles": "1CH",
        "2 Chronicles": "2CH",
        "Ezra": "EZR",
        "Nehemiah": "NEH",
        "Esther": "EST",
        "Job": "JOB",
        "Psalm": "PSA",
        "Proverbs": "PRO",
        "Ecclesiastes": "ECC",
        "Song of Solomon": "SNG",
        "Isaiah": "ISA",
        "Jeremiah": "JER",
        "Lamentations": "LAM",
        "Ezekiel": "EZK",
        "Daniel": "DAN",
        "Hosea": "HOS",
        "Joel": "JOL",
        "Amos": "AMO",
        "Obadiah": "OBA",
        "Jonah": "JON",
        "Micah": "MIC",
        "Nahum": "NAM",
        "Habakkuk": "HAB",
        "Zephaniah": "ZEP",
        "Haggai": "HAG",
        "Zechariah": "ZEC",
        "Malachi": "MAL",
        "Matthew": "MAT",
        "Mark": "MRK",
        "Luke": "LUK",
        "John": "JHN",
        "Acts": "ACT",
        "Romans": "ROM",
        "1 Corinthians": "1CO",
        "2 Corinthians": "2CO",
        "Galatians": "GAL",
        "Ephesians": "EPH",
        "Philippians": "PHP",
        "Colossians": "COL",
        "1 Thessalonians": "1TH",
        "2 Thessalonians": "2TH",
        "1 Timothy": "1TI",
        "2 Timothy": "2TI",
        "Titus": "TIT",
        "Philemon": "PHM",
        "Hebrews": "HEB",
        "James": "JAS",
        "1 Peter": "1PE",
        "2 Peter": "2PE",
        "1 John": "1JN",
        "2 John": "2JN",
        "3 John": "3JN",
        "Jude": "JUD",
        "Revelation": "REV"
    ]
    
    static func getRandomScripture() -> Scripture {
        return scriptures.randomElement() ?? Scripture(text: "Be still, and know that I am God.", reference: "Psalm 46:10")
    }
    
    static func generateYouVersionURL(for reference: String) -> String? {
        let components = reference.split(separator: " ")
        guard components.count >= 2,
              let chapterVerse = components.last?.split(separator: ":"),
              chapterVerse.count == 2,
              let chapter = chapterVerse.first,
              let verse = chapterVerse.last else {
            print("Invalid reference format: \(reference)")
            return nil
        }
        
        let bookComponents = components.dropLast().joined(separator: " ")
        guard let osisBook = osisBookMap[bookComponents] else {
            print("Book not found in OSIS map: \(bookComponents)")
            return nil
        }
        
        // Use the YouVersion URL format for KJV (version 1)
        let formattedReference = "\(osisBook).\(chapter).\(verse)".replacingOccurrences(of: " ", with: "")
        let urlString = "https://www.bible.com/bible/1/\(formattedReference)"
        guard let encodedURLString = urlString.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) else {
            print("Failed to encode URL for: \(urlString)")
            return nil
        }
        
        return encodedURLString
    }
}
