struct ScriptureProvider {
    static let scriptures = [
        "Your word is a lamp to my feet and a light to my path. - Psalm 119:105",
        "Trust in the Lord with all your heart and lean not on your own understanding. - Proverbs 3:5",
        "I can do all things through Christ who strengthens me. - Philippians 4:13",
        "Be strong and courageous. Do not be afraid or terrified because of them, for the Lord your God goes with you. - Deuteronomy 31:6",
        "The Lord is my shepherd; I shall not want. - Psalm 23:1",
        "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life. - John 3:16",
        "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. - Philippians 4:6",
        "Fear thou not; for I am with thee: be not dismayed; for I am thy God. - Isaiah 41:10",
        "In the beginning God created the heaven and the earth. - Genesis 1:1",
        "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you. - Matthew 6:33",
        "Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners. - Psalm 1:1",
        "Thy word have I hid in mine heart, that I might not sin against thee. - Psalm 119:11",
        "And we know that all things work together for good to them that love God. - Romans 8:28",
        "Cast thy burden upon the Lord, and he shall sustain thee. - Psalm 55:22",
        "Come unto me, all ye that labour and are heavy laden, and I will give you rest. - Matthew 11:28",
        "The fear of the Lord is the beginning of wisdom. - Proverbs 9:10",
        "What time I am afraid, I will trust in thee. - Psalm 56:3",
        "Delight thyself also in the Lord: and he shall give thee the desires of thine heart. - Psalm 37:4",
        "Be strong and of a good courage; be not afraid, neither be thou dismayed. - Joshua 1:9",
        "Jesus saith unto him, I am the way, the truth, and the life. - John 14:6",
        "Commit thy works unto the Lord, and thy thoughts shall be established. - Proverbs 16:3",
        "Blessed are the pure in heart: for they shall see God. - Matthew 5:8",
        "Wait on the Lord: be of good courage, and he shall strengthen thine heart. - Psalm 27:14",
        "Let not your heart be troubled: ye believe in God, believe also in me. - John 14:1",
        "The Lord is my light and my salvation; whom shall I fear? - Psalm 27:1",
        "Peace I leave with you, my peace I give unto you. - John 14:27",
        "Every word of God is pure: he is a shield unto them that put their trust in him. - Proverbs 30:5",
        "God is our refuge and strength, a very present help in trouble. - Psalm 46:1",
        "Rejoice in the Lord always: and again I say, Rejoice. - Philippians 4:4",
        "Thou wilt keep him in perfect peace, whose mind is stayed on thee. - Isaiah 26:3",
        "Ask, and it shall be given you; seek, and ye shall find. - Matthew 7:7",
        "Have not I commanded thee? Be strong and of a good courage. - Joshua 1:9",
        "My help cometh from the Lord, which made heaven and earth. - Psalm 121:2",
        "The Lord is nigh unto them that are of a broken heart. - Psalm 34:18",
        "Thy kingdom is an everlasting kingdom. - Psalm 145:13",
        "Be ye kind one to another, tenderhearted, forgiving one another. - Ephesians 4:32",
        "The Lord will give strength unto his people. - Psalm 29:11",
        "Call unto me, and I will answer thee. - Jeremiah 33:3",
        "If God be for us, who can be against us? - Romans 8:31",
        "O give thanks unto the Lord; for he is good. - Psalm 136:1",
        "Let every thing that hath breath praise the Lord. - Psalm 150:6",
        "The Lord is good, a strong hold in the day of trouble. - Nahum 1:7",
        "Ye are the light of the world. A city that is set on an hill cannot be hid. - Matthew 5:14",
        "Draw nigh to God, and he will draw nigh to you. - James 4:8",
        "The joy of the Lord is your strength. - Nehemiah 8:10",
        "I will lift up mine eyes unto the hills, from whence cometh my help. - Psalm 121:1",
        "Love one another; as I have loved you. - John 13:34",
        "The Lord bless thee, and keep thee. - Numbers 6:24",
        "Faith is the substance of things hoped for, the evidence of things not seen. - Hebrews 11:1",
        "The Lord is merciful and gracious, slow to anger, and plenteous in mercy. - Psalm 103:8",
        "With God all things are possible. - Matthew 19:26",
        "Study to shew thyself approved unto God. - 2 Timothy 2:15",
        "Great is thy faithfulness. - Lamentations 3:23",
        "Blessed are they that mourn: for they shall be comforted. - Matthew 5:4",
        "The Lord is my strength and my shield. - Psalm 28:7",
        "Rest in the Lord, and wait patiently for him. - Psalm 37:7",
        "Behold, I stand at the door, and knock. - Revelation 3:20",
        "Give, and it shall be given unto you. - Luke 6:38",
        "He that dwelleth in the secret place of the most High shall abide under the shadow of the Almighty. - Psalm 91:1",
        "Let your light so shine before men. - Matthew 5:16",
        "The effectual fervent prayer of a righteous man availeth much. - James 5:16",
        "Be not deceived; God is not mocked. - Galatians 6:7",
        "The Lord shall fight for you, and ye shall hold your peace. - Exodus 14:14",
        "Seek ye the Lord while he may be found. - Isaiah 55:6",
        "I am the vine, ye are the branches. - John 15:5",
        "Blessed are the peacemakers: for they shall be called the children of God. - Matthew 5:9",
        "The Lord is gracious, and full of compassion. - Psalm 111:4",
        "Trust in him at all times; ye people, pour out your heart before him. - Psalm 62:8",
        "Go ye therefore, and teach all nations. - Matthew 28:19",
        "Thou art my hiding place and my shield. - Psalm 119:114",
        "Humble yourselves in the sight of the Lord, and he shall lift you up. - James 4:10",
        "The Lord is on my side; I will not fear. - Psalm 118:6",
        "Let all your things be done with charity. - 1 Corinthians 16:14",
        "Thy testimonies are very sure. - Psalm 93:5",
        "Heaven and earth shall pass away, but my words shall not pass away. - Matthew 24:35",
        "I will never leave thee, nor forsake thee. - Hebrews 13:5",
        "The fear of the Lord is the beginning of knowledge. - Proverbs 1:7",
        "Be still, and know that I am God. - Psalm 46:10",
        "Keep thy tongue from evil, and thy lips from speaking guile. - Psalm 34:13",
        "Ye shall know the truth, and the truth shall make you free. - John 8:32",
        "The Lord is good unto them that wait for him. - Lamentations 3:25",
        "Praise ye the Lord: for it is good to sing praises unto our God. - Psalm 147:1",
        "Whatsoever ye do, do it heartily, as to the Lord. - Colossians 3:23",
        "The Lord is my rock, and my fortress. - Psalm 18:2",
        "Confess your faults one to another, and pray one for another. - James 5:16",
        "O taste and see that the Lord is good. - Psalm 34:8",
        "Thy righteousness is like the great mountains. - Psalm 36:6",
        "I am come that they might have life, and that they might have it more abundantly. - John 10:10",
        "The Lord upholdeth all that fall, and raiseth up all those that be bowed down. - Psalm 145:14",
        "Be of good cheer; it is I; be not afraid. - Matthew 14:27",
        "His compassions fail not. - Lamentations 3:22",
        "Walk in love, as Christ also hath loved us. - Ephesians 5:2",
        "The Lord preserveth the faithful. - Psalm 31:23",
        "By grace are ye saved through faith. - Ephesians 2:8",
        "Thou hast turned for me my mourning into dancing. - Psalm 30:11",
        "The meek shall inherit the earth. - Psalm 37:11",
        "Teach me thy way, O Lord, and lead me in a plain path. - Psalm 27:11",
        "My grace is sufficient for thee. - 2 Corinthians 12:9",
        "Let us love one another: for love is of God. - 1 John 4:7",
        "Create in me a clean heart, O God; and renew a right spirit within me. - Psalm 51:10",
        "The heavens declare the glory of God; and the firmament sheweth his handywork. - Psalm 19:1",
        "Cast all your care upon him; for he careth for you. - 1 Peter 5:7",
        "In all thy ways acknowledge him, and he shall direct thy paths. - Proverbs 3:6",
        "The name of the Lord is a strong tower: the righteous runneth into it, and is safe. - Proverbs 18:10",
        "And ye shall seek me, and find me, when ye shall search for me with all your heart. - Jeremiah 29:13",
        "The Lord is slow to anger, and great in power. - Nahum 1:3",
        "But my God shall supply all your need according to his riches in glory. - Philippians 4:19",
        "He that covereth his sins shall not prosper: but whoso confesseth and forsaketh them shall have mercy. - Proverbs 28:13",
        "For I know the thoughts that I think toward you, saith the Lord, thoughts of peace. - Jeremiah 29:11",
        "Blessed are they which do hunger and thirst after righteousness: for they shall be filled. - Matthew 5:6",
        "The Lord is my portion, saith my soul; therefore will I hope in him. - Lamentations 3:24",
        "Submit yourselves therefore to God. Resist the devil, and he will flee from you. - James 4:7",
        "Whoso keepeth his mouth and his tongue keepeth his soul from troubles. - Proverbs 21:23",
        "Thou art my refuge and my fortress: my God; in him will I trust. - Psalm 91:2",
        "For whosoever shall call upon the name of the Lord shall be saved. - Romans 10:13",
        "The grass withereth, the flower fadeth: but the word of our God shall stand for ever. - Isaiah 40:8",
        "Let no corrupt communication proceed out of your mouth. - Ephesians 4:29",
        "Thou, Lord, art good, and ready to forgive. - Psalm 86:5",
        "He that spared not his own Son, but delivered him up for us all. - Romans 8:32",
        "Speak, Lord; for thy servant heareth. - 1 Samuel 3:9",
        "The Lord redeemeth the soul of his servants. - Psalm 34:22",
        "Order my steps in thy word: and let not any iniquity have dominion over me. - Psalm 119:133",
        "Whoso findeth me findeth life, and shall obtain favour of the Lord. - Proverbs 8:35",
        "The Lord thy God in the midst of thee is mighty. - Zephaniah 3:17",
        "Finally, brethren, whatsoever things are true, whatsoever things are honest, think on these things. - Philippians 4:8",
        "My soul, wait thou only upon God; for my expectation is from him. - Psalm 62:5",
        "Except the Lord build the house, they labour in vain that build it. - Psalm 127:1",
        "He that is slow to anger is better than the mighty. - Proverbs 16:32",
        "The Lord is righteous in all his ways, and holy in all his works. - Psalm 145:17",
        "If we confess our sins, he is faithful and just to forgive us our sins. - 1 John 1:9",
        "Thy mercy, O Lord, is in the heavens; and thy faithfulness reacheth unto the clouds. - Psalm 36:5",
        "Return unto thy rest, O my soul; for the Lord hath dealt bountifully with thee. - Psalm 116:7",
        "The fear of the Lord prolongeth days. - Proverbs 10:27",
        "O Lord, thou art my God; I will exalt thee, I will praise thy name. - Isaiah 25:1",
        "Ye are bought with a price; therefore glorify God in your body. - 1 Corinthians 6:20",
        "The Lord shall preserve thee from all evil: he shall preserve thy soul. - Psalm 121:7",
        "To every thing there is a season, and a time to every purpose under the heaven. - Ecclesiastes 3:1",
        "He hath shewed thee, O man, what is good; and what doth the Lord require of thee. - Micah 6:8",
        "Be ye therefore perfect, even as your Father which is in heaven is perfect. - Matthew 5:48",
        "Thou hast also given me the shield of thy salvation. - 2 Samuel 22:36",
        "The Lord will perfect that which concerneth me. - Psalm 138:8",
        "Open thou mine eyes, that I may behold wondrous things out of thy law. - Psalm 119:18",
        "Keep thy heart with all diligence; for out of it are the issues of life. - Proverbs 4:23",
        "For the Lord giveth wisdom: out of his mouth cometh knowledge and understanding. - Proverbs 2:6",
        "Blessed is he whose transgression is forgiven, whose sin is covered. - Psalm 32:1",
        "I have set the Lord always before me: because he is at my right hand, I shall not be moved. - Psalm 16:8",
        "Behold, how good and how pleasant it is for brethren to dwell together in unity. - Psalm 133:1",
        "The Lord is far from the wicked: but he heareth the prayer of the righteous. - Proverbs 15:29",
        "Look unto me, and be ye saved, all the ends of the earth. - Isaiah 45:22",
        "A new heart also will I give you, and a new spirit will I put within you. - Ezekiel 36:26"
    ]
    
    static func getRandomScripture() -> String {
        return scriptures.randomElement() ?? "Be still, and know that I am God. - Psalm 46:10"
    }
}
